name: Platformer
version: '${project.version}'
main: xamyr.net.platformer.Platformer
api-version: 1.18
authors: [ Xamyr ]
description: moving platforms
depend: [WorldEdit]
commands:
  platformcreate:
    description: Create a moving platform
    usage: /<command> <1.8/>1.8> <direction> <Move-No-Blocks> <wait-time> <speed> <name>
    aliases: [platcreate, pcreate]
    permission: platformer.create
  platformdelete:

