## mcparkour configuration
---
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: mcparkour
  username: root
  password: meow
levels:
  base: 200
  addition: 60
spawn:
  world: world
  x: 0.5
  y: 64.0
  z: 0.5
  pitch: 0.0
  yaw: 0.0
duel:
 bounty:
   minimum: 10
   maximum: 10000