name: ${project.name}
version: ${project.version}
description: ${project.description}
author: cmastudios
website: ${project.url}
main: ${main.class}
commands:
  parkour:
    description: Teleport to a parkour course
    usage: /<command> <numer parkoura> - teleportuje na dany parkour
    aliases: [pk, kz]
    permission: parkour.play
  setcourse:
    description: Set the teleport for a parkour course
    usage: /<command> <course-number> <detection-range> <normal/vip/adventure/guildwar> <easy/medium/hard>
    aliases: [pkset]
    permission: parkour.set
  listcourses:
    description: List all valid parkour courses
    usage: /<command>
    aliases: [pklist]
    permission: parkour.play
  deletecourse:
    description: Delete the teleport for a parkour course
    usage: /<command> <course-number>
    aliases: [pkdelete, pkdel, pkremove, pkrm]
    permission: parkour.delete
  topscores:
    description: View top scores for a parkour course
    usage: /<command> <numer-parkoura> [strona] - Wyswietla wszystkie czasu na danym parkourze
    aliases: [pktop]
    permission: parkour.play
  checkpoint:
    description: Set a checkpoint in the current course to your location
    usage: /<command>
    aliases: [cp]
    permission: parkour.cp
  duel:
    description: Start or accept request to begin a parkour duel.
    usage: |
      /<command> <nazwa gracza> <numer parkourar> <stawka> - wyzywa przeciwnika na duel.
      /<command> accept <stawka> - akceptuje wyzwanie na duel
      /<command> decline - odrzuca wyzwanie.
    permission: parkour.play
  lvl:
    description: View player level and experience.
    usage: |
      /<command> - wyswietla statystyki doswiadczenia
      /<command> <nick-gracza> - Wyswietla statystyki innego gracza
    aliases: [level, poziom]
    permission: parkour.play
  guild:
    description: Guild management
    usage: |
      /<command> create <tag> <nazwa> - Tworzy gildie
      /<command> invite <nazwa gracza> - zaprasza do gildii
      /<command> accept <tag> - akceptuje zaproszenie
      /<command> decline - odrzuca zaproszenie
      /<command> leave - odchodzi z gildii. jesli gildia jest pusta zostaje ona usunieta.
      /<command> kick <nazwa gracza> - wyrzuca gracza z gildii
      /<command> rank <nazwa gracza> <ranga> - zmienia range danego gracza
      /<command> chat - Wlacza/wylacza chat gildyjny
      /<command> war <tag> <course> - Wyzywa gildie na danej mapie
      /<command> war <tag> - Akceptuje wyzwanie do walki
      /<command> war decline - Odrzuca wyzwanie do walki.
  adventure:
    description: Manage adventure parkour courses
    permission: parkour.play
    aliases: [adv, advcontinue, advset, advadd]
    usage: |
      /<command> <adventure course> - Teleport to adventure course
      /<command> <adventure course> <chapter> - Teleport to specific adventure chapter
      /<command> <adventure course> add <course> - (admn) Add course to adventure
permissions:
  parkour.play:
    description: Required in order to play parkour
  parkour.set:
    description: Required in order to set teleports for courses or to create control signs
  parkour.tpexempt:
    description: Exempt a player from being teleported back to spawn on join.
  parkour.guild.create:
    description: Power to create a guild
  parkour.vip:
    description: Permission to play on VIP maps

