name: ${project.name}
version: ${project.version}
description: ${project.description}
author: cmastudios
website: ${project.url}
main: ${main.class}
commands:
  parkour:
    description: Teleport to a parkour course
    usage: /<command> <course-number>
    aliases: [pk, kz]
    permission: parkour.play
  setcourse:
    description: Set the teleport for a parkour course
    usage: /<command> <course-number> <detection-range> <normal/vip/adventure/guildwar> <easy/medium/hard>
    aliases: [pkset]
    permission: parkour.set
  listcourses:
    description: List all valid parkour courses
    usage: /<command>
    aliases: [pklist]
    permission: parkour.play
  deletecourse:
    description: Delete the teleport for a parkour course
    usage: /<command> <course-number>
    aliases: [pkdelete, pkdel, pkremove, pkrm]
    permission: parkour.delete
  topscores:
    description: View top scores for a parkour course
    usage: /<command> <course-number> [page]
    aliases: [pktop]
    permission: parkour.play
  checkpoint:
    description: Set a checkpoint in the current course to your location
    usage: /<command>
    aliases: [cp]
    permission: parkour.cp
  duel:
    description: Start or accept request to begin a parkour duel.
    usage: |
      /<command> <nazwa gracza> <numer parkourar> <stawka> - wyzywa przeciwnika na duel.
      /<command> accept <stawka> - akceptuje wyzwanie na duel
      /<command> decline - odrzuca wyzwanie.
    permission: parkour.play
  lvl:
    description: View player level and experience.
    usage: |
      /<command> - View your level and XP.
      /<command> <player-name> - View another player's level and XP.
    permission: parkour.play
  guild:
    description: Guild management
    usage: |
      /<command> create <tag> <name> - Create a guild
      /<command> invite <player> - Invite player to join guild
      /<command> accept <tag> - Accept invite to guild
      /<command> decline - Decline invite to guild
      /<command> leave - Leave your guild. If it will empty, it will be destroyed.
      /<command> kick <player> - Remove player from guild.
      /<command> rank <player> <rank> - Change player rank
      /<command> chat - Toggle guild chat status
      /<command> war <tag> <course> - Declare war on guild at course
      /<command> war <tag> - Accept war with guild
      /<command> war decline - Decline war with guild
permissions:
  parkour.play:
    description: Required in order to play parkour
  parkour.set:
    description: Required in order to set teleports for courses or to create control signs
  parkour.tpexempt:
    description: Exempt a player from being teleported back to spawn on join.
  parkour.guild.create:
    description: Power to create a guild

