name: ${project.name}
version: ${project.version}
description: ${project.description}
author: cmastudios
website: ${project.url}
main: ${main.class}
commands:
  parkour:
    description: Teleport to a parkour course
    usage: /<command> <course-number>
    aliases: [pk]
    permission: parkour.play
  setcourse:
    description: Set the teleport for a parkour course
    usage: /<command> <course-number>
    aliases: [pkset]
    permission: parkour.set
  topscores:
    description: View top scores for a parkour course
    usage: /<command> <course-number> [page]
    aliases: [pktop]
    permission: parkour.play
  checkpoint:
    description: Set a checkpoint in the current course to your location
    usage: /<command>
    aliases: [cp]
    permission: parkour.cp
permissions:
  parkour.play:
    description: Required in order to play parkour
  parkour.set:
    description: Required in order to set teleports for courses or to create control signs
  parkour.tpexempt:
    description: Exempt a player from being teleported back to spawn on join.

