## mcparkour configuration
---
mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: mcparkour
  username: root
  password: meow
spawn:
  world: world
  x: 0.5
  y: 64.0
  z: 0.5
  pitch: 0.0
  yaw: 0.0
duel:
 bounty:
   minimum: 10
   maximum: 10000
restriction:
  easy: 0
  medium: 8
  hard: 16
  veryhard: 24
  duel: 8
  levelRequiredToUsePkCommand: 8
events:
  distance:
    scoredplaces: 3
    preferredTimeInterval: 5-8
    rewards:
        1: 500
        2: 400
        3: 300
  plays:
    scoredplaces: 3
    preferredTimeInterval: 3-6
    rewards:
        1: 500
        2: 400
        3: 300
  time:
    scoredplaces: 3
    preferredTimeInterval: 4-5
    rewards:
        1: 500
        2: 400
        3: 300
pkrooms:
  easy:
    x: 607
    y: 83
    z: 565
    pitch: 4.65
    yaw: -180
    world: pk
  medium:
    x: 607 
    y: 83
    z: 564
    pitch: 4.65
    yaw: -180
    world: pk
  hard:
    x: 607 
    y: 83
    z: 564
    pitch: 4.65
    yaw: -180
    world: pk
  veryhard:
    x: 607 
    y: 83
    z: 564
    pitch: 4.65
    yaw: -180
    world: pk