name: ${project.name}
version: ${project.version}
description: ${project.description}
author: cmastudios
authors: [maciekmm]
website: ${project.url}
depend: [Experience]
softdepend: [BarAPI]
api-version: 1.18
main: ${main.class}
commands:
  parkour:
    description: Teleport to a parkour course
    usage: /<command> <numer parkoura> - teleportuje na dany parkour
    aliases: [pk, kz]
    permission: parkour.play
  setcourse:
    description: Set the teleport for a parkour course
    usage: /<command> <course-number> <detection-range> <normal/vip/adventure/guildwar/thematic/hidden/event/custom> <easy/medium/hard> <name>
    aliases: [pkset]
    permission: parkour.set
  listcourses:
    description: List all valid parkour courses
    usage: /<command> [adventure]
    aliases: [pklist]
    permission: parkour.play
  deletecourse:
    description: Delete the teleport for a parkour course
    usage: /<command> <course-number>
    aliases: [pkdelete, pkdel, pkremove, pkrm]
    permission: parkour.delete
  topscores:
    description: View top scores for a parkour course
    usage: /<command> <numer-parkoura> [strona] - Wyswietla wszystkie czasu na danym parkourze
    aliases: [pktop]
    permission: parkour.play
  highscores:
    description: Manage highscores
    usage: |
      /<command> reset player <player> - resets player's highscores
      /<command> reset course <course> - resets all highscores on specified course
      /<command> reset course <course> <player> - resets all player's highscores on specified course
    aliases: [highscore, wyniki,hs]
    permission: parkour.highscores
  checkpoint:
    description: Set a checkpoint in the current course to your location
    usage: /<command>
    aliases: [cp]
    permission: parkour.cp
  see:
    description: Add player to exempts list when in blind mode
    usage: /<command> <player>
    aliases: [ogladaj]
    permission: parkour.see
  duel:
    description: Start or accept request to begin a parkour duel.
    usage: |
      /<command> <player name> <parkour number> <bounty> - Sends duel invitation to opponent.
      /<command> accept <bounty> - Accepts duel invitation
      /<command> decline - Declines the invitation
    permission: parkour.play
  pkroom:
    description: Parkour rooms
    usage: /<command> <room>
    aliases: [easy,normal,medium,hard,veryhard,adventure,thematic,tematyczne,przygodowe]
    permission: parkour.play
  ratio:
    description: Set global ratio
    usage: |
      /<command> set <amount> - Sets global ratio
      /<command> - Gets global ratio
      /<command> get - Gets global ratio
    permission: parkour.ratio
  guild:
    description: Guild management
    usage: |
      /<command> create <tag> <name> - Creates a guild
      /<command> invite <player name> - Invites a player to guild
      /<command> accept <tag> - Accepts guild invitation
      /<command> decline - Declines the invitation
      /<command> leave - Leaves guild, if you are the only member and you leave the guild gets removed.
      /<command> kick <player name> - Kick player the from guild
      /<command> rank <player name> <rank> - Changes players guild rank.
      /<command> chat - Toggles guild chat
      /<command> war <tag> <course> - Sends war invitation.
      /<command> war <tag> - Accepts war invitation
      /<command> war decline - Declines the war invitation
  adventure:
    description: Manage adventure parkour courses
    permission: parkour.play
    aliases: [adv, advcontinue, advset, advadd]
    usage: |
      /<command> <adventure course> - Teleport to adventure course
      /<command> <adventure course> <chapter> - Teleport to specific adventure chapter
      /<command> <adventure course> add <course> - (admn) Add course to adventure
  event:
    description: Manage events
    permission: parkour.event
    aliases: [rush]
    usage: |
      /<command> - Teleports to event
      /<command> start <minutes> <course> - Starts an event course
      /<command> end - Ends an event
      /<command> create <parkour> <TIME_RUSH/PLAY_RUSH/GATE_RUSH> - Creates an event
  custom:
    description: Manage custom parkours
    permission: parkour.custom
    aliases: [effectcourse]
    usage: |
      /<command> create <id> <effect:amplifier>... - Creates custom map
      /<command> delete <id> - Deletes custom map
  vanish:
    description: Vanish from cruel world
    permission: parkour.vanish.command
    aliases: [vsh,disappear,zniknij]
    usage: /<command> - Vanishes
permissions:
  parkour.*:
    description: All parkour permissions
    default: op
    children:
        parkour.admin: true
        parkour.player: true
        parkour.vip: true
  parkour.admin:
    description: Admin permissions
    default: false
    children:
        parkour.set: true
        parkour.tpexempt: true
        parkour.teleport: true
        parkour.custom: true
        parkour.bypasslevel: true
        parkour.ignoreteleport: true
        parkour.fly.bypass: true
        parkour.vanish: true
  parkour.player:
    description: Basic player permissions
    default: true
    children:
        parkour.play: true
        parkour.duel: true
        parkour.highscore: true
        parkour.guild.join: true
        parkour.event: true
        parkour.cp: true
        parkour.see: true
  parkour.vanish:
    default: false
    description: Vanish command
    childer:
        parkour.vanish.command: true
        parkour.vanish.seevanished: true
  parkour.cp:
    description: Allows you to use checkpoints
  parkour.fly.bypass:
    description: Allows you to score highscores with fly.
  parkour.see:
    description: Allows you to use see command
  parkour.event:
    description: Required to play event parkours
  parkour.custom:
    description: Required to create custom courses
  parkour.play:
    description: Starting courses, teleporting to maps
  parkour.highscore:
    description: Required to achieve highscores.
  parkour.duel:
    description: Required play duels
  parkour.set:
    description: Required in order to set teleports for courses or to create control signs
  parkour.teleport:
    description: Required in order to teleport to hidden parkours
  parkour.tpexempt:
    description: Exempt a player from being teleported back to spawn on join.
  parkour.guild.join:
    description: Allows player to be in guild
  parkour.guild.create:
    description: Power to create a guild
  parkour.ignoreteleport:
    description: Does not stop parkour when teleporting
  parkour.vip:
    description: Permission to play on VIP maps and get VIP stuff
  parkour.bypasslevel:
    description: Permission to bypass level restrictions
  parkour.vanish.seevanished:
    description: Allows you to see vanished people
  parkour.vanish.command:
    description: Allows you to vanish
  parkour.vanish.alwaysvanished:
    description: Person is always hidden from others