name: ${project.name}
version: ${project.version}
description: ${project.description}
author: maciekmm
authors: [cmastudios]
website: ${project.url}
main: ${main.class}
api-version: 1.18
commands:
  modifier:
    description: Checks modifier
    usage: /<command> - Check your modifier
    aliases: [mnoznik]