name: ParkourDonations
version: '${project.version}'
main: xamyr.net.parkourdonations.ParkourDonations
api-version: 1.18
load: STARTUP
authors: [ Xamyr ]
description: ParkourLive donations handler
commands:
  ParkourDonate:
    description: Parkour donation command
    usage: /<command> <type> <parkour id> <minutes> <player name>
    aliases: [pkdonate, pkdon]
    permission: pkdonation.add
