mysql:
  enabled: false
  host: 127.0.0.1
  port: 3306
  database: mcparkour
  username: root
  password: meow
  playerstable: false  #Enable only if running without parkour plugin
levels:
  base: 200
  addition: 60