name: ${project.name}
version: ${project.version}
description: ${project.description}
author: cmastudios
authors: [maciekmm]
website: ${project.url}
main: ${main.class}
api-version: 1.18
commands:
  exp:
    description: Manage player''s experience
    usage: |
          /<command> set <player> <xp> - set player's xp
          /<command> add <player> <xp> - add xp to player
    aliases: [experience]
    permission: experience.admin
  lvl:
    description: View player level and experience.
    usage: |
      /<command> - Shows your current level and experience
      /<command> <player-name> - Displays other player's level and experience
    aliases: [level, poziom]
    permission: parkour.play